name: Publish Module

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish-module:
    name: Tag Release and Publish to Forge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - name: Set Metadata
        run: 'cat ./metadata.json | jq .version=\"${GITHUB_REF##*/}\" > ./md.json && mv ./md.json metadata.json'
      - name: Get Version
        id: gv
        run: |
          echo "::set-output name=ver::$(jq --raw-output .version metadata.json)"
      - name: Install the PDK
        run: |
          source /etc/os-release
          wget https://apt.puppet.com/puppet-tools-release-${UBUNTU_CODENAME}.deb
          sudo dpkg -i puppet-tools-release-${UBUNTU_CODENAME}.deb
          rm -f puppet-tools-release-${UBUNTU_CODENAME}.deb
          sudo apt-get update
          sudo apt-get install pdk
          pdk bundle install
      - name: Validate Docs
        run: |
          set -e
          documentation=$(pdk bundle exec puppet strings generate --format markdown)
          if [ $(echo $documentation | grep -Ec "[1-9]+ undocumented|\[warn\]") -gt 0 ]; then
            echo "Please resolve documentation issues detected below:"
            echo $documentation
            exit 1
          fi
      - name: Tag Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gv.outputs.ver }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
      - name: Build Module
        run: pdk build
      - name: Push to Forge
        run: pdk release publish --forge-token ${{ secrets.FORGE_API_KEY }} --force
